CREATE TABLE [dbo].[TASKS]
(
  [ID] INT NOT NULL PRIMARY KEY,
  [TITLE] NVARCHAR(255) NULL,
  [DESCRIPTION] NVARCHAR(MAX) NULL,
  [DEADLINE] DATETIME NULL,
  [LISTID] INT NOT NULL,
  [DONE] BIT NOT NULL,
  [PRIORITY] INT NOT NULL,
)
